xbmc/skin.confluence

720p/DialogPVRRadioRDSInfo.xml
This fixes the switch between normal and classical music on the RDS Radiotext+ dialog
=> Fix classical RadiotextPlus music view

720p/DialogAudioDSPManager.xml, addon.xml, changelog.txt, language/resource.language.en_gb/strings.po
- Updated settings layout
- Remove the set of ADSP manager dialog list types, becomes done from
Kodi itself
=> [skin.confluence] v3.0.11

720p/Includes.xml, addon.xml, changelog.txt
- Show addon status if available, instead of size
=> [skin.confluence] v3.0.26

720p/VideoOSD.xml
^^
no point showing those values if pvrplayback.signalquality is false. as readings wont make any sense, anyway.
=> [chg] codecinfo: conditionaly show pvr signal quality

720p/MyPVRRecordings.xml
Removes secondary icon from details in recordings list
- This provides more space for the plot and
- avoids a long-standing problem on RPi which causes scrolling the list to be painfully slow
Before:
After:
(note this image also includes the change in https://github.com/xbmc/skin.confluence/pull/22)
=> Remove secondary icon from Recordings list

720p/MyPVRChannels.xml
the info is reduntant. so let's keep the small media window clean
before: http://i.imgur.com/IIdHPJr.jpg
after: http://i.imgur.com/3GI2l4Y.jpg
=> [cleanup] remove media label from MyPVRChannels

720p/MyPVRChannels.xml
cosmetics. crecording icon looked stretched
before: http://i.imgur.com/GRWo6Xx.jpg
after: http://i.imgur.com/7zl5SBF.jpg
=> [fix] MyPVRChannels.xml: recording icon size

720p/DialogAddonSettings.xml
a poor attempt to make addon settings work after https://github.com/xbmc/xbmc/pull/12125
this needs testing, I am really bad at skinning and not sure I am doing the positioning right
DialogAddonSettings.xml is now basicaly same as DialogSettings.xml with some small changes:
- control id 9001 is re-positioned to fit the new "defaults" button.
- added conrtols for categories area on top.
here is the diff http://sprunge.us/PgVa
=> [chg] add-ons/settings: adjust for xbmc/pull/12125

720p/IncludesHomeMenuItems.xml
LE 7.0 (and OE before) patched an extra tab under Settings on the homescreen to facilitate easier access to our settings/configuration add-on, e.g. 
https://github.com/LibreELEC/LibreELEC.tv/blob/libreelec-7.0/packages/mediacenter/kodi-theme-Confluence/patches/kodi-theme-Confluence-001-add_oe_settings_to_homescreen.patch
Users who update to LE 8.0/9.0 and install the repo version of Confluence often cannot find the settings add-on under Add-ons > Program Add-on's or they just moan about this shortcut not being present. So this PR adds it back, but conditionally, like how we add a link in Estuary:
https://github.com/phil65/skin.estuary/blob/master/xml/Settings.xml#L114-L119
=> add conditional shortcut for LibreELEC settings

720p/Includes.xml
The Default movie scraper (TMDB) uses 'NR' for Not Rated movies. This change fixes the tag recognition.
=> Recognize NR as Not Rated for mpaa tag

720p/Home.xml
Currently, when users navigate down from the main menu items in the ```Home``` window, the active control becomes the ```Power``` button.  Accessing the favorites requires one more navigation to the left.  I think it's much more likely that users would want quick and direct access to their ```Favorites``` (hence the name), rather than quick and direct access to shut down their home theater software.
This pull request modified [Home.xml](../blob/master/720p/Home.xml) to allow navigation directly to the favorites button from the main menu items.
=> Navigating down from the "Home" window's menu should take you directly to "Favorites"

720p/DialogPVRInfo.xml, 720p/DialogSeekBar.xml, 720p/Home.xml, 720p/Includes.xml, 720p/VideoFullScreen.xml, language/resource.language.en_gb/strings.po
This PR fixes incorrectly displayed times when playing LiveTV content with EPG.
Before the fix, incorrect time/duration was displayed while seeking/timeshifting, progress bars did not work.
Incorrect start time and end time was displayed in full video screen, PVR Info and Home screens.
=> [skin.confluence] Fix LiveTV with EPG elapsed time and duration

720p/Home.xml
According to GUIInfoManager.cpp, Weather.Conditions returns "Current weather conditions as textual description". So, to show a weather icon on the upper left of the home screen this must be changed with weather.ConditionsIcon
=> Restore home weather icon

720p/Includes.xml, 720p/IncludesBackgroundBuilding.xml, 720p/MyMusicNav.xml, 720p/MyPlaylist.xml, 720p/ViewsMusicLibrary.xml, language/resource.language.en_gb/strings.po
Users want to be able to view playlist and for the currently playing track details to be shown, the present Media Info view only shows the details of the selected track.
The design for the new "Now playing" view was based on the existing "Media info" view with some modifcations:
The existing "Media info" then was aligned for a match in style:
For comparison old "Media info"
**Implementation notes**
- As the design of "Media info" and "Now playing" matches then the info box is titled so you easily know which view you are in.
- With old "Media info" view if the text was too long then it would scroll, with both new "Media info" and "Now Playing" I've given enough room to wrap to 2 lines for long text string as shown by artist name and track title in above images.
- Rather than restrict this …
=> New "Now playing" view aligned to "Media Info"

720p/Includes.xml, 720p/SkinSettings.xml, language/resource.language.en_gb/strings.po
As we already have that at Estuary: https://github.com/xbmc/xbmc/pull/14007
I thought adding that for Confluence might also be a pretty good idea. 
I've tested what happens if Kodi gets mutet and the name as well as the avatar moving to the left for the muting icon.
If some music is playing, the location of the currently playing track is different from Estuary. It's not at the top, it's nearly in the middle of the screen. So neither the clock nor the profile identifiert is affected. 
Let me know if something needs to be changed.
=> Add setting for profile identification

720p/ViewsMusicLibrary.xml
In the PR38 Disc was hard labelled and I forgot to change it to a localised label.
=> Fix missing label localisation

720p/Home.xml, 720p/IncludesBackgroundBuilding.xml, 720p/IncludesHomeRecentlyAdded.xml, 720p/SkinSettings.xml, language/resource.language.en_gb/strings.po
I added very simple and basic changes to have a kids/parents profile. This is based on the "master" lock and allows you to hide/show main menu items for both the normal users and those that have the master lock disabled.
I also added the option to add playlists for under the movie/tvshow/albums buttons. 
It all is very basic, so let me know if things need changing.
=> Added: changes for a very simple 'kids/master' profile

720p/DialogSeekBar.xml, 720p/VideoFullScreen.xml
The changes at "DialogSeekBar.xml" introducing an additional section showing the end time of a video at the top of a screen if the player is paused/seeking/etc and the videoOSD is not shown.
The changes at "FullScreenVideo.xml" is a typo fix, where I would say this happened by accident.
Open for comments and suggestions ;)
Screenshot:
=> Add 'End time' control and visibility

720p/Home.xml, 720p/IncludesHomeMenuItems.xml
I know, we talked about it and some ppl didn't like it, but here is what I have had already done and I thought it's worth PRing it
This change adds a submenu for the add-ons home menu entry and also probably kind of fixes #50 or probably gives less confusion.
=> Add add-ons submenu

720p/VideoFullScreen.xml
As we spoke about that at forums: 
https://forum.kodi.tv/showthread.php?tid=342673&pid=2844077#pid2844077
and at slack, this is the fix to show the endtime of a video at the video-info screen.
=> Fix endtime visibility for video info screen

720p/ViewsVideoLibrary.xml
I added the video duration to the PosterWrapView. It was there before, but in a different look. I made it compliant to #55:
Also added a visible condition to make the duration invisible if the "Parent Folder" is focused (thanks @HitcherUK for the hint ;) )
As I merged #55 myself and I have missed to test every scenario, I also changed a little bit of the alignment and the position of the duration-label at the MediaInfoView for movies and episodes as especially for episodes there was an overlap for the aired and the duration labels: 
The changes for the other sections are more to set the duration label at the same position and also make them invisible if the "Parent Folder"-item was selected.
Hope this is still fine in a single PR. If not, then feel free to close and I create multiple PRs …
=> View layout changes

language/resource.language.en_gb/strings.po
Let's make our addon checker happy ;)
Added spaces after every `#` where it hasn't been a `.` or `:` or `|`
=> Fix comments in strings.po file

720p/IncludesHomeRecentlyAdded.xml, addon.xml, changelog.txt
This PR will switch to dynamic content for all home screen widgets.
This has a lot of benefits:
- Faster
- Code cleanup (250+ less lines)
- Fanart is available and set
- Context menus are working
- Information windows can be opened directly from widgets
Also fixes the issue mentioned here: https://forum.kodi.tv/showthread.php?tid=356715
=> Dynamic content for home screen widgets

720p/IncludesHomeRecentlyAdded.xml, addon.xml, changelog.txt
This PR adds:
- Home screen widgets show only unwatched items
- Increase widgets to contain 15 items (before 10)
=> Home screen widgets show only unwatched items

720p/VideoFullScreen.xml
This fixes the issue where the subtitles icon is visible even is subtitles are disabled.
master branch
Fixes:
#104
#78
=> [master] Fix subtitles icon

720p/VideoFullScreen.xml
This fixes the issue where the subtitles icon is visible even is subtitles are disabled.
Matrix branch
Fixes:
https://github.com/xbmc/skin.confluence/issues/104
https://github.com/xbmc/skin.confluence/issues/78
=> [Matrix] Fix subtitles icon

720p/VideoFullScreen.xml
This fixes the issue where the subtitles icon is visible even is subtitles are disabled.
Leia branch (if it's still supported?)
Fixes:
https://github.com/xbmc/skin.confluence/issues/104
https://github.com/xbmc/skin.confluence/issues/78
=> [Leia] Fix subtitles icon

720p/Home.xml, 720p/IncludesHomeRecentlyAdded.xml, 720p/SkinSettings.xml, language/resource.language.en_gb/strings.po
Matrix branch version of https://github.com/xbmc/skin.confluence/pull/140
Placement of the Search button looks out of place.
This has been raised a few times on the forum see https://forum.kodi.tv/showthread.php?tid=363918 and https://forum.kodi.tv/showthread.php?tid=355958&pid=2966342#pid2966342
Search would seem to be more appropriate to have along the Power/Favourites buttons
As we have settings to Hide/Show for everything else displayed on Home, I've also added settings to allow hiding of the new Search button and the existing Favourites button
=> [Matrix] Move search & add home screen button settings

720p/Defaults.xml
Use the new tags texturesliderbardisabled and textureslidernibdisabled added in Kodi v21 for more consistent disabled look of the slider bar in settings.
* Apply diffuse color to match the style of other disabled controls
Used the same diffuse color as disabled textures of other controls in Confluence for simplicity.
Picked osd_slider_bg instead of osd_slider_bgNF because the extra alpha makes it almost invisible.
Tested on v21 (change is visible) and v20 (new tags are ignored and there is no effect).
Enabled:
Before PR (slider partly disabled):
After PR (fully disabled):
=> Use new v21 tags for slider control's disabled appearance

720p/IncludesHomeRecentlyAdded.xml
Currently episode images are always shown on the home page. This PR fixes that behavior an hides it when configured.
=> Honor spoiler settings on home view

1080p/VideoOSD.xml, 1080p/custom_OptionsDialog.xml, 1080p/custom_PlaySpeed.xml
Remove tool tip menu's for Play Speed and Stereoscopic 3D mode.
Add new `custom_OptionsDialog.xml` this provides a new Options menu and provide the menu for Stereoscopic 3D mode options.
New `Options` menu has:
**Play speed** (moved from old tool tip menu)
**Player process info** (new osd access to this)
**Colour Management** (new osd access to this)
Add new `custom_PlaySpeed.xml` to provide **Play speed** control
New `Stereoscopic 3D mode` menu
I also the took the oportunity to clean up the grouplists and button id's in `VideoOSD.xml`
The group of buttons to the left are in Grouplist id `100`
All button in the grouplist are in id range `101 `to `111 `to show they belong to Grouplist id `100`
The group of buttoms to the right are now in a seperate Grouplist id `200`
All button in the …
=> Add new custom dialog providing access to play speed/3D

1080p/VideoOSD.xml
Fix https://github.com/xbmc/skin.confluence/issues/286
Missing teletext button after osd button refactor contained in https://github.com/xbmc/skin.confluence/pull/283
=> Teletext button fix [Master]

1080p/VideoOSD.xml
Fix https://github.com/xbmc/skin.confluence/issues/286
Missing teletext button after osd button refactor contained in https://github.com/xbmc/skin.confluence/pull/284
There was also a stray commented out onup I got to remove.
=> Teletext button fix [Omega]

1080p/DialogMusicInfo.xml
Hi,
with this PR i want to add the Play button on the music info dialog like on Estuary, it's an handy thing when you dig into the artist discography.
I'm not an expert skinner and it's my first contribution, so let me know if the proposed solution could be ok :)
Here some screens
=> Add play button on music info dialog

1080p/DialogPlayerProcessInfo.xml, language/resource.language.en_gb/strings.po
Break player process up in a similar manner to Estuary which has tabs for each type of info
**Estuary Player Process**
I felt the Estuary style tab buttons wouldn't suit Confluence so after searching through Confluence I decided best fit would the style used for the submenus.
So the submenu **Files / Library / Add-ons** style.
**Note -** the info shown in the **Media** tab was not shown in Confluence Player Process window before.
**PVR**
**Player**
**Media**
**System**
=> [Master] Refactor player process

1080p/Home.xml, 1080p/MyWeather.xml, 1080p/ViewsWeather.xml
Replaced usage of Window.Property and other legacy info tags with Weather.Data throughout Home.xml, MyWeather.xml, and ViewsWeather.xml for consistency and improved compatibility. Also removed temperature unit labels from weather views and updated icon and texture references to use the new property structure.
=> Refactor weather XMLs to use Weather.Data properties
