xbmc/skin.confluence

- 720p/MusicVisualisation.xml
- 720p/VideoFullScreen.xml
- addon.xml
- changelog.txt
> [skin.confluence] v3.0.3

- 720p/script-globalsearch-main.xml
> Fix globalsearch scrollbar

- 720p/Settings.xml
- language/resource.language.en_gb/strings.po
@HitcherUK as promised
I've not removed the strings for the old layout as I wasn't sure if they were needed for backwards compatibility.
@ronie I guess the cleanup is needed here as well after all,was nervous about removing stuff in case I broke anything. If so I can redo and resubmit tomorrow.
> Update for settings layout changes

- 720p/Settings.xml
Change label from Library to Media to reflect changes in https://github.com/xbmc/xbmc/pull/10199
> [confluence] label update

- 720p/MyPVRRecordings.xml
Adds Season/Episode to the PVR recordings screen as per https://github.com/xbmc/xbmc/pull/11000
> [PVR] Add Season/Episode to Recordings list

- 720p/VideoFullScreen.xml
It was accidentally deleted by a57f776.
> [skin.confluence] Restore view mode/sizing info

- 720p/VideoFullScreen.xml
- addon.xml
also includes addon version bump, I can drop it if not (yet) wanted.
> minor fix for pull/26 

- 720p/Includes.xml
- 720p/ViewsMusicLibrary.xml
Refactor my previous work to modernise the code, reduce duplication, and make it slightly slicker from user perspective using techniques I've learnt since my original PR from studying the Estuary code.
Font has also been slightly decreased to make better use of available space.
> Refactor media info / now playing views

- 720p/ViewsVideoLibrary.xml
I am using this parameter almost as often as movie description when choosing Movie for evening. Nobody wants to start watching good movie, and find it too long later, when tiredness kicks in :)
> Add Video duration into View

- addon.xml
- language/resource.language.en_gb/strings.po
Fixes addon.xml:
- forum link changed to https
- removed website and email tags
Fixes strings.po:
- add space after `#`
> Addon.xml and strings.po comment block fixes

- language/resource.language.en_gb/strings.po
> Fix comments in strings.po file

- 720p/IncludesHomeMenuItems.xml
CoreELEC is great option for AML devices, let them enjoy Confluence skin with platform specific settings button the same way as LibreELEC do...
> Added CoreELEC compatibility

- addon.xml
- changelog.txt
- language/resource.language.en_gb/strings.po
- language/resource.language.es_es/strings.po
- language/resource.language.pl_pl/strings.po
- language/resource.language.ro_ro/strings.po
This PR includes the language updates which have been done for the master branch. I rebased the Leia branch on those commits and also backported the changelog updates
> Language files and changlog backports

- changelog.txt
Added the missing notes for the changelog.txt
> changelog updates

- 720p/DialogVideoInfo.xml
Fix browse button (id=8) in DialogVideoInfo.xml for sets.
> [skin.confluence] Fix DialogVideoInfo.xml browse button

- 720p/DialogAddonSettings.xml
Add settings level button (id=20) to DialogAddonSettings.xml
> [skin.confluence] Add settings level button

- 720p/Home.xml
- 720p/IncludesHomeMenuItems.xml
- 720p/IncludesHomeRecentlyAdded.xml
- 720p/MyWeather.xml
- addon.xml
- changelog.txt
- Bump xbmc.gui
- Add System.AddonIsEnabled()
- Add EnableAddon()
> Changes for v19

- 720p/IncludesHomeMenuItems.xml
- 720p/ViewsVideoLibrary.xml
> Minor fixes

- 720p/Home.xml
- 720p/VideoFullScreen.xml
Poster fix for master branch.
As mentioned here: https://forum.kodi.tv/showthread.php?tid=360346&pid=3014082#pid3014082
@jjd-uk
> Fix posters

- 720p/MusicOSD.xml
- 720p/MusicVisualisation.xml
- addon.xml
- changelog.txt
This PR will fix the PVR radio record button for Leia branch.
It will also fix the PVR radio recording label.
As reported here: #93
@Max11223344 please check if this fixes your issue.
@jjd-uk as mentioned at Slack
> Fix MusicOSD.xml record button

- 720p/MusicOSD.xml
- 720p/MusicVisualisation.xml
- addon.xml
- changelog.txt
This replaces https://github.com/xbmc/skin.confluence/pull/94
Everything is tested in previous PR.
> Fix MusicOSD.xml record button and record label

- 720p/DialogAddonInfo.xml
- addon.xml
- changelog.txt
Add "Versions" button to DialogAddonInfo.xml
https://forum.kodi.tv/showthread.php?tid=343076&pid=3017736#pid3017736
> Add button id=14 to DialogAddonInfo.xml

- 720p/IncludesHomeMenuItems.xml
- 720p/ViewsVideoLibrary.xml
- Fix BOM in IncludesHomeMenuItems.xml
- Fix BOM in ViewsVideoLibrary.xml
- Change labels 416 (not existing anymore) to 10005 ("Not available")
> Remove BOM and fix not existing labels

- .github/workflows/sync-addon-metadata-translations.yml
Workflow to sync `summary`, `description` and `disclaimer` between addon.xml and language files.
When changes are made either for addon.xml or any language file, a PR will be created to sync these changes.
> [Matrix] Create sync-addon-metadata-translations.yml

- 720p/Home.xml
- 720p/IncludesHomeRecentlyAdded.xml
- 720p/SkinSettings.xml
- language/resource.language.en_gb/strings.po
Placement of the Search button looks out of place.
This has been raised a few times on the forum see https://forum.kodi.tv/showthread.php?tid=363918 and https://forum.kodi.tv/showthread.php?tid=355958&pid=2966342#pid2966342
Search would seem to be more appropriate to have along the Power/Favourites buttons
As we have settings to Hide/Show for everything else displayed on Home, I've also added settings to allow hiding of the new Search button and the existing Favourites button
> [Master] Move search & add home screen button settings

- 720p/Includes.xml
- 720p/Includes_DialogSelect.xml
- addon.xml
- changelog.txt
This will fix the missing image in DialogSelect.xml
BP of https://github.com/xbmc/skin.confluence/pull/170
> Fix missing image in DialogSelect.xml

- 1080p/DialogSelect.xml
- 1080p/IncludesDialogSelect.xml
- addon.xml
- changelog.txt
[Add 'Check Previous Episode' layout](https://github.com/xbmc/skin.confluence/commit/868ed776e79b1fb612d8873a3f8e749622994959)
> Add 'Check Previous Episode' layout

- 1080p/DialogPlayerProcessInfo.xml
- language/resource.language.en_gb/strings.po
Backport of https://github.com/xbmc/skin.confluence/pull/296
> [Omega] Refactor player process

- 1080p/DialogVideoInfo.xml
Align video info flags with rest of skin
> Update dialog video info
